//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG_Tickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesTicket
    {
        public int dt_id { get; set; }
        public Nullable<int> tk_id_ticket { get; set; }
        public string dt_titulo { get; set; }
        public string dt_comentario { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
