//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG_Tickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaForo
    {
        public int eforo_id { get; set; }
        public Nullable<int> foro_id { get; set; }
        public Nullable<int> eforo_id_usuario { get; set; }
        public string eforo_titulo { get; set; }
        public string eforo_descripcion { get; set; }
        public string eforo_es_solucion { get; set; }
    
        public virtual Foro Foro { get; set; }
    }
}
