//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG_Tickets
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Foro()
        {
            this.EntradaForos = new HashSet<EntradaForo>();
        }
    
        public int foro_id { get; set; }
        public string foro_tema { get; set; }
        public string foro_tipo { get; set; }
        public string foro_fecha_cierre { get; set; }
        public Nullable<int> cli_id { get; set; }
        public Nullable<int> tec_id { get; set; }
        public string foro_is_verificado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntradaForo> EntradaForos { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
