//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG_Tickets
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGDataEntities : DbContext
    {
        public SIGDataEntities()
            : base("name=SIGDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<DetallesTicket> DetallesTickets { get; set; }
        public virtual DbSet<Entidades_Externas> Entidades_Externas { get; set; }
        public virtual DbSet<EntradaForo> EntradaForos { get; set; }
        public virtual DbSet<Foro> Foros { get; set; }
        public virtual DbSet<Tecnico> Tecnicos { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
    }
}
